# Bunker 1-1 5.55 + 0.55 made by Bar0ti https://youtu.be/H-hkGc4_E8o
# Maybe it's possible to improve

from katas import Controller, Scripter
#strat 1 is 5.55 strat 2 is 5.57
STRAT = 1

script = Scripter()

if STRAT == 1:
    script.Button(Controller.left_shoulder, 0)
    script.Wait(2)
    script.Button(Controller.down, duration=1)
    script.Wait(1)
    script.Roll()
    script.Wait(11)
    script.Button(Controller.left, duration=6)
    script.Button(Controller.A, duration=0)
    script.Button(Controller.left_thumb, duration=0)
    script.Wait(2)
    script.Button(Controller.down, duration=1)
    script.Wait(3)
    script.Button(Controller.down, duration=1)
    script.Wait(1)
    script.Roll()
    script.Wait(8)
    script.MoveLeftStick(179.2)
    script.Button(Controller.X, duration=0)
    script.Wait(4)
    script.Button(Controller.down, duration=1)
    script.Wait(1)
    script.Roll()
    script.Wait(10)
    script.Button(Controller.left_thumb, duration=0)
    script.Wait(3)
    script.Button(Controller.down, duration=1)
    script.Wait(1)
    script.Roll()
    script.Wait(4)
    script.Button(Controller.Y, duration=0)
    script.Wait(6)
    script.Button(Controller.left, duration=6)
    script.Button(Controller.A, duration=0)
    script.Button(Controller.left_thumb, duration=0)
    script.Wait(2)
    script.Button(Controller.down, duration=1)
    script.Wait(3)
    script.Button(Controller.down, duration=1)
    script.Wait(1)
    script.Roll()
if STRAT == 2:
    script.Button(Controller.left_shoulder, 0)
    script.Wait(2)
    script.Button(Controller.down, duration=1)
    script.Wait(1)
    script.Roll()
    script.Wait(16)
    script.MoveLeftStick(179.413)
    script.Button(Controller.X, duration=0)
    script.Wait(8)
    script.Button(Controller.down, duration=1)
    script.Wait(1)
    script.Roll()
    script.Wait(10)
    script.Button(Controller.left_thumb, duration=0)
    script.Wait(3)
    script.Button(Controller.down, duration=1)
    script.Wait(1)
    script.Roll()
    script.Wait(8)
    script.Button(Controller.Y, duration=0)
    script.Wait(2)
    script.MoveLeftStick(180)
    script.Button(Controller.X, duration=0)
    script.Wait(11)
    script.Button(Controller.down, duration=1)
    script.Wait(1)
    script.Roll()
script.save()

#slow-mo
#script.Button(Controller.left_thumb, duration=0)

#scuffed slow-mo c-slashing timings
#script.MoveLeftStick(0.8)
#script.Button(Controller.X, duration=0)
#script.Wait(11)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(3)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)

#c-slash timings
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.MoveLeftStick(0)
#script.Button(Controller.X, duration=0)
#script.Wait(11)


