# Bunker 1-2 6.93 made by Bar0ti https://youtu.be/iZND5zXrKNs
# Pretty much guaranteed to be improvable, you can most likely kill the shotgunner earlier which would save time but it'd introduce rng elements,
# you probably can find a timing to do the ricky boost sooner, and I did not bother to check through the angles of ricky boosts to determine which ones are faster
 

from katas import Controller, Scripter

script = Scripter()
script.Button(Controller.left_shoulder, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(12)
script.Button(Controller.X, duration=1)
script.Wait(9)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(18)
script.Button(Controller.X, duration=1)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.X, duration=1)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(7)
script.Button(Controller.X, duration=1)
script.Wait(18)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(7)
script.MoveLeftStick(35)
script.Button(Controller.X, duration=1)
script.Wait(1)
script.Button(Controller.right, duration=24)
script.Button(Controller.B, duration=1)
script.Wait(3)
script.Button(Controller.B, duration=1)
script.Wait(3)
script.Button(Controller.B, duration=1)
script.Wait(17)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(2)
script.Button(Controller.Y, duration=1)
script.save()
