# Bunker 1-5 6.80 made by Bar0ti https://youtu.be/uvf9ZleQBeg
# High chance of improving it

from katas import Controller, Scripter

script = Scripter()
script.Button(Controller.left_shoulder, duration=0)
script.Wait(2)
script.Button(Controller.dpad_down, duration=6)
script.Wait(1)
script.Roll()
script.Wait(19)
script.MoveLeftStick(180)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.dpad_down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(5)
script.MoveLeftStick(66)
script.Button(Controller.B, duration=0)
script.Wait(10)
script.MoveLeftStick(180)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.dpad_down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(12)
script.MoveLeftStick(140)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.dpad_down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(20)
#script.Button(Controller.dpad_down, duration=2)
#script.Wait(1)
#script.Roll()
script.Wait(1)
script.MoveLeftStick(135)
script.Button(Controller.X, duration=0)
script.Wait(8)
script.Button(Controller.dpad_down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(14)
script.MoveLeftStick(350)
script.Button(Controller.X, duration=0)
script.Wait(3)
script.Button(Controller.dpad_left, duration=2)
script.Button(Controller.dpad_down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(9)
script.Button(Controller.Y, duration=0)
script.Wait(10)
script.Button(Controller.X, duration=0)
script.save()
