# Bunker 1-5 6.80 and other variants made by Bar0ti https://youtu.be/uvf9ZleQBeg
# High chance of improving it

from katas import Controller, Scripter

# change the value of STRAT to use other variations of this room
# STRAT 1 - 6.80 - fastest so far
# STRAT 2 - 6.87 - the end is done with roll and slash to the elevator 6.88
# STRAT 3 - 6.88 - the end is done with roll cancel 6.90
# STRAT 4 - WIP  - the end is done with frame perfect crouch roll work in progress
STRAT = 1

script = Scripter()
script.Button(Controller.left_shoulder, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=6)
script.Wait(1)
script.Roll()
script.Wait(19)
script.MoveLeftStick(180)
script.Button(Controller.X, duration=0)

if STRAT == 1:
  script.Wait(5)
  script.Button(Controller.down, duration=2)
  script.Wait(1)
  script.Roll()
  script.Wait(5)
  script.MoveLeftStick(66)
  script.Button(Controller.B, duration=0)
  script.Wait(10)
  script.MoveLeftStick(180)
  script.Button(Controller.X, duration=0)
  script.Wait(4)
  script.Button(Controller.down, duration=2)
  script.Wait(1)
  script.Roll()
  script.Wait(12)
  script.MoveLeftStick(140)
  script.Button(Controller.X, duration=0)
  script.Wait(4)
  script.Button(Controller.down, duration=2)
  script.Wait(1)
  script.Roll()
  script.Wait(20)
  script.Wait(1)
  script.MoveLeftStick(135)
  script.Button(Controller.X, duration=0)
  script.Wait(8)
  script.Button(Controller.down, duration=2)
  script.Wait(1)
  script.Roll()
  script.Wait(14)
  script.MoveLeftStick(350)
  script.Button(Controller.X, duration=0)
  script.Wait(3)
  script.Button(Controller.left, duration=2)
  script.Button(Controller.down, duration=2)
  script.Wait(1)
  script.Roll()
  script.Wait(9)
  script.Button(Controller.Y, duration=0)
  script.Wait(10)
  script.Button(Controller.X, duration=0)
  
if STRAT > 1:
  script.Wait(6)
  script.Roll()
  script.Wait(18)
  script.MoveLeftStick(180)
  script.Button(Controller.X, duration=0)
  script.Wait(4)
  script.Roll()
  script.Wait(11)
  script.MoveLeftStick(145)
  script.Button(Controller.X, duration=0)
  script.Wait(4)
  script.Button(Controller.down, duration=2)
  script.Wait(1)
  script.Roll()
  script.Wait(9)
  script.Button(Controller.A, duration=1)
  script.Wait(4)
  script.Button(Controller.down, duration=3)
  script.Wait(2)
  script.Roll()
  script.Wait(4)
  script.MoveLeftStick(40)
  script.Button(Controller.B, duration=0)
  
  if STRAT == 2:
    script.Wait(14)
    script.MoveLeftStick(140)
    script.Button(Controller.X, duration=0)
    script.Wait(3)
    script.Button(Controller.down, duration=2)
    script.Wait(1)
    script.Roll()
    script.Wait(18)
    script.Button(Controller.Y, duration=0)
    script.Wait(3)
    script.Wait(1)
    script.Button(Controller.X, duration=0)
    script.Wait(10)
    script.Button(Controller.down, duration=2)
    script.Wait(1)
    script.Roll()
    
  if STRAT == 3:
    script.Wait(18)
    script.MoveLeftStick(140)
    script.Button(Controller.X, duration=0)
    script.Wait(3)
    script.Button(Controller.down, duration=2)
    script.Wait(1)
    script.Roll()
    script.Wait(16)
    script.Button(Controller.A, duration=1)
    script.Wait(1)
    script.Button(Controller.Y, duration=0)
    script.Wait(1)    
    script.Button(Controller.down, duration=2)
    script.Wait(2)
    script.Roll()
    
  if STRAT == 4:
    script.Wait(18)
    script.Button(Controller.down, duration=2)
    script.Wait(1)
    script.Roll()
    script.Wait(2)
    script.MoveLeftStick(165)
    script.Button(Controller.X, duration=0)
    script.Wait(6)
    script.Button(Controller.down, duration=2)
    script.Wait(2)
    script.Roll()
    script.Wait(9)
    script.Button(Controller.Y, duration=0)

script.save()
