# Bunker 1-7 8.77 made by Bar0ti https://youtu.be/r-buc5_FwDA
# Guaranteed to be possible to be improvable upon, I couldn't be arsed to produce a proper TAS for this room
# Paths that were TAS'ed to see if they end up being faster:
# 1. going through the top path by just briefly dropping to the below floor to aggro the gunner
# 2. Doing the strat that's in this TAS but not throwing the smoke grenade, it's slower due to the fact that you cannot kill the gunner and shotgunner that come out quickly enough with deflects
 

from katas import Controller, Scripter

script = Scripter()
script.Button(Controller.left_shoulder, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(230)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=17)
script.Button(Controller.left, duration=17)
script.Wait(17)
script.MoveLeftStick(275)
script.Button(Controller.X, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=8)
script.Button(Controller.left, duration=30)
script.Wait(6)
script.Roll()
script.Wait(6)
script.Button(Controller.X, duration=0)
script.Wait(15)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.X)
script.Wait(11)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.X)
script.Wait(11)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.X)
script.Wait(11)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Button(Controller.B, duration=16)
script.Roll()
script.Wait(10)
script.Button(Controller.left, duration=16)
script.Button(Controller.A, duration=16)
script.Wait(16)
script.MoveLeftStick(105)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.right, duration=12)
script.Wait(13)
script.MoveLeftStick(20)
script.Button(Controller.X, duration=0)
script.Wait(10)
script.Button(Controller.down, duration=16)
script.Wait(6)
script.MoveLeftStick(330)
script.Button(Controller.X, duration=0)
script.Wait(16)
script.MoveLeftStick(350)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.left, duration=4)
script.Button(Controller.down, duration=4)
script.Wait(2)
script.Roll()
script.Wait(10)
script.Button(Controller.X)
script.Wait(11)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.X)
script.Wait(4)
script.Button(Controller.Y)
script.Wait(7)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.save()
