# Bunker 1-9 8.77 made by Bar0ti https://www.youtube.com/watch?v=o9p3WielzR0

from katas import Controller, Scripter

script = Scripter()
script.Button(Controller.left_shoulder, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=22)
script.Roll()
script.Wait(22)
script.Roll()
script.Wait(18)
#ricky slash
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=0)
script.Roll()
script.Wait(12)
#door slash
script.Button(Controller.X, duration=0)
script.Wait(10)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(15)
#dropping down slash
script.MoveLeftStick(220)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=38)
script.Button(Controller.left, duration=16)
script.Wait(14)
script.Roll()
script.Wait(18)
#double gunner slash
script.MoveLeftStick(180)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.right, duration=10)
script.Wait(5)
script.Roll()
script.Wait(14)
#deflect to gain height
script.MoveLeftStick(90)
script.Button(Controller.X, duration=0)
script.Wait(8)
script.Button(Controller.A, duration=20)
script.Wait(8)
#last gunner slash onto the platform
script.MoveLeftStick(145)
script.Button(Controller.X, duration=0)
script.Wait(6)
script.Button(Controller.down, duration=66)
script.Roll()
script.Wait(22)
script.Button(Controller.down, duration=1)
script.Roll()
script.Wait(22)
script.MoveLeftStick(180)
script.Button(Controller.X, duration=0)
script.Wait(14)
script.Button(Controller.down, duration=1)
script.Roll()
script.Wait(15)
script.Button(Controller.Y, duration=0)
script.Wait(7)
script.Roll()
script.Wait(7)
script.save()
