# Bunker 1-9 8.77

from katas import Controller, Scripter

script=Scripter()
script.Button(Controller.left_shoulder, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=0)
script.Roll(1)
script.Wait(22)
script.Button(Controller.down, duration=0)
script.Roll(1)
script.Wait(18)
#ricky slash
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=0)
script.Roll(1)
script.Wait(12)
#door slash
script.Button(Controller.X, duration=0)
script.Wait(10)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll(1)
script.Wait(16)
script.MoveLeftStick(220)
#dropping down slash
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=16)
script.Button(Controller.left, duration=16)
script.Roll(16)
script.Wait(32)
#double gunner slash
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.right, duration=10)
script.Wait(5)
script.Roll()
script.Wait(14)
script.MoveLeftStick(90)
#deflect to gain height
script.Button(Controller.X, duration=0)
script.Wait(8)
script.Button(Controller.A, duration=20)
script.Wait(8)
script.MoveLeftStick(140)
#last gunner slash onto the platform
script.Button(Controller.X, duration=0)
script.Wait(7)
script.Button(Controller.down, duration=1)
script.Roll()
script.Wait(22)
script.Button(Controller.down, duration=1)
script.Roll()
script.Wait(22)
script.Button(Controller.down, duration=1)
script.Roll()
script.Wait(22)
script.Button(Controller.down, duration=1)
script.Roll()
script.Wait(7)
script.Button(Controller.Y, duration=0)
script.Wait(4)
script.Button(Controller.left, duration=12)
script.save()