# Bunker 1-9 8.00 made by Bar0ti https://youtu.be/VIxBuMmtHc8
# Very likely chance of improving

from katas import Controller, Scripter

script = Scripter()
script.Button(Controller.left_shoulder, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=22)
script.Roll()
script.Wait(22)
script.Roll()
script.Wait(18)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=0)
script.Roll()
script.Wait(12)
script.Button(Controller.X, duration=0)
script.Wait(10)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(11)
#this jump to the 2nd ledge is likely possible to optimize further
#since you can jump onto the ledge in many ways that I haven't tested
script.MoveLeftStick(210)
script.Button(Controller.X, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(9)
script.Button(Controller.left, duration=15)
script.Button(Controller.A, duration=15)
script.Wait(16)
script.MoveLeftStick(260)
script.Button(Controller.X, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(22)
script.MoveLeftStick(220)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(20)
script.MoveLeftStick(340)
script.Button(Controller.B, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(0)
script.Button(Controller.left, duration=2)
script.MoveLeftStick(335)
script.Button(Controller.B, duration=0)
script.Wait(3)
#this entry to the elevator is unoptimized, it's likely that you can delay the
#slash for a few frames and then roll on the first frame that it lets you
#however the moment I fiddle with these two variables, I no longer am able
#to open the elevator 6 frames after rolling, but only after 7
#to change those two variables you will need to fiddle with the slash angle
#it should change your position in small enough increments to allow you to
#activate the elevator only after 6 frames
script.MoveLeftStick(180)
script.Button(Controller.X, duration=0)
script.Wait(16)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(6)
script.Button(Controller.Y, duration=0)
script.Wait(15)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.save()

