# Bunker 1-10 4.87 made by Bar0ti https://youtu.be/G0AGYS_REe0
# Guaranteed to be possible to be improvable upon, but that depends on how much rng are you willing to stomach :)
# One strat to try is to do a ricky boost, as shown here https://www.youtube.com/watch?v=RqT-ZXCFO1Y
 

from katas import Controller, Scripter

script = Scripter()
script.Button(Controller.left_shoulder, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.X, duration=0)
script.Wait(9)
script.Button(Controller.right, duration=40)
script.Button(Controller.A, duration=14)
script.Wait(17)
script.MoveLeftStick(85)
script.Button(Controller.X, duration=0)
script.Wait(17)
script.MoveLeftStick(70)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(10)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.right, duration=14)
script.Button(Controller.down, duration=14)
script.Wait(12)
script.Button(Controller.B, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(8)
script.MoveLeftStick(220)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=16)
script.Button(Controller.right, duration=18)
script.Wait(14)
script.MoveLeftStick(330)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=8)
script.Wait(7)
script.Roll()
script.Wait(5)
script.Button(Controller.B, duration=0)
script.Wait(6)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.Y, duration=0)
script.Wait(10)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(1)
script.Button(Controller.B, duration=0)
script.Wait(1)

script.save()
