# Bunker 2-1 made by Bar0ti https://youtu.be/NK1iLC8NK0s
# Guaranteed to be improvable

from katas import Controller, Scripter
script = Scripter()

script.Button(Controller.left_shoulder, 0)
script.Wait(2)
script.Button(Controller.right, duration=9)
script.Button(Controller.A, duration=9)
script.Button(Controller.left_thumb, duration=0)
script.Wait(10)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.MoveLeftStick(5.175)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.right, duration=9)
script.Button(Controller.down, duration=9)
script.Wait(10)
script.MoveLeftStick(298.5)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=15)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(3)
script.Button(Controller.X, duration=0)
script.Wait(6)
script.Button(Controller.left, duration=5)
script.Button(Controller.down, duration=12)
script.Wait(23)
script.MoveLeftStick(170)
script.Button(Controller.X, duration=0)
script.Wait(6)
script.Button(Controller.left, duration=8)
script.Button(Controller.down, duration=12)
script.Wait(6)
script.MoveLeftStick(210)
script.Button(Controller.X, duration=0)
script.Button(Controller.left, duration=7)
script.Wait(1)
script.Button(Controller.down, duration=13)
script.Wait(7)
script.Button(Controller.right, duration=10)
script.Wait(10)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(5)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(6)
script.MoveLeftStick(240.8)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.left, duration=12)
script.Button(Controller.down, duration=12)
script.Wait(14)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(1)
script.MoveLeftStick(180)
script.Button(Controller.B, duration=0)
script.Wait(5)
script.Button(Controller.A, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=10)
script.Wait(5)
script.Button(Controller.right, duration=15)
script.Wait(4)
script.MoveLeftStick(350)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.MoveLeftStick(270)
script.Button(Controller.X, duration=0)
script.Button(Controller.right, duration=4)
script.Wait(1)
script.Button(Controller.down, duration=12)
script.Wait(8)
script.Button(Controller.left, duration=7)
script.Wait(7)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(6)
script.Button(Controller.A, duration=0)
script.Wait(9)
script.Button(Controller.down, duration=4)
script.Wait(4)
script.MoveLeftStick(266)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=12)
script.Wait(7)
script.Button(Controller.right, duration=12)
script.Wait(4)
script.MoveLeftStick(330)
script.Button(Controller.X, duration=0)
script.Wait(6)
script.Button(Controller.down, duration=12)
script.Wait(1)
script.Roll()
script.Wait(6)
script.MoveLeftStick(268)
script.Button(Controller.X, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=10)
script.Button(Controller.left, duration=12)
script.Wait(13)
script.Button(Controller.down, duration=7)
script.Wait(1)
script.Roll()
script.Wait(1)
script.MoveLeftStick(170)
script.Button(Controller.B, duration=0)
script.Wait(8)
script.Button(Controller.A, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=10)
script.Wait(1)
script.Button(Controller.right, duration=8)
script.Wait(8)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=10)
script.Button(Controller.right, duration=10)
script.Wait(11)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=16)
script.Button(Controller.right, duration=20)
script.Wait(22)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.MoveLeftStick(0.8)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(8)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.save()

#slow-mo
#script.Button(Controller.left_thumb, duration=0)

#c-slash timings
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.MoveLeftStick(0)
#script.Button(Controller.X, duration=0)
#script.Wait(11)

#scuffed slow-mo c-slashing timings
#script.MoveLeftStick(0.8)
#script.Button(Controller.X, duration=0)
#script.Wait(11)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(3)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)

#slow-mo roll cancel timings
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(11)
#script.Button(Controller.right, duration=6)
#script.Button(Controller.A, duration=0)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(2)
#script.Button(Controller.down, duration=1)
#script.Wait(3)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
