#Bunker 2-1 8s made by Bar0ti https://www.youtube.com/watch?v=IY00lhBbD5Q
#Guaranteed to be done faster

from katas import Controller, Scripter
    
script = Scripter()
script.Button(Controller.left_shoulder, duration=0)
script.Wait(2)
script.Button(Controller.A, duration=11)
script.Button(Controller.right, duration=11)
script.Wait(12)
script.Button(Controller.X, duration=0)
script.Wait(16)
script.Button(Controller.down, duration=44)
script.Roll()
script.Wait(22)
script.Roll()
script.Wait(8)
script.MoveLeftStick(10)
script.Button(Controller.X, duration=0)
script.Button(Controller.right, duration=12)
script.Wait(11)
script.Button(Controller.X, duration=0)
script.Button(Controller.down, duration=12)
script.Wait(23)
script.MoveLeftStick(115)
script.Button(Controller.X, duration=0)
script.Button(Controller.left, duration=15)
script.Wait(6)
script.Button(Controller.down, duration=9)
script.Wait(8)
script.MoveLeftStick(200)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.left, duration=8)
script.Button(Controller.down, duration=25)
script.Wait(8)
script.Button(Controller.right, duration=16)
script.Wait(20)
script.MoveLeftStick(10)
script.Button(Controller.X, duration=0)
script.Wait(6)
script.Button(Controller.left, duration=16)
script.Button(Controller.down, duration=30)
script.Wait(8)
script.MoveLeftStick(180)
script.Button(Controller.B, duration=0)
script.Wait(24)
script.MoveLeftStick(290)
script.Button(Controller.X, duration=0)
script.Wait(2)
script.Button(Controller.right, duration=20)
script.Button(Controller.down, duration=20)
script.Wait(22)
script.MoveLeftStick(30)
script.Button(Controller.X, duration=0)
script.Wait(3)
script.Button(Controller.left, duration=30)
script.Button(Controller.down, duration=30)
script.Wait(28)
#I didn't bother checking out at which exactly frame to slash, too much work :pensive:
script.MoveLeftStick(160)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.right, duration=30)
script.Button(Controller.down, duration=30)
script.Wait(7)
script.MoveLeftStick(330)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.MoveLeftStick(330)
script.Button(Controller.X, duration=0)
script.Wait(13)
script.Button(Controller.B, duration=0)
script.Wait(2)
script.MoveLeftStick(250)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.B, duration=0)
script.Button(Controller.left, duration=13)
script.Button(Controller.down, duration=13)
script.Wait(20)
script.Button(Controller.A, duration=1)
script.Wait(1)
script.Button(Controller.down, duration=10)
script.Wait(8)
#I am sure that this following section can be done faster
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Button(Controller.right, duration=100)
script.Wait(8)
script.Button(Controller.down, duration=28)
script.Wait(28)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=36)
script.Wait(36)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.PerfectRollWait(3)
script.save()
