# Bunker 2-1 7.58 made by Bar0ti https://www.youtube.com/watch?v=7dzzppl2xgg
# There's still a high chance of improving the TAS, though expect a ton of time on doing so
# The TAS looks solid until the 5th floor, I wouldn't expect that you'd be able to easily shave a bunch of
# time in there. However the story changes starting from the 5th floor, there's still a ton of possibilities at
# approaching the way to deal with those enemies, and there's still the possibility of just ignoring the cleaver
# and just killing the shotgunner with a bullet deflect. 

from katas import Controller, Scripter


script = Scripter()
script.Button(Controller.left_shoulder, duration=0)
script.Wait(2)
script.Button(Controller.A, duration=13)
script.Button(Controller.right, duration=13)
script.Wait(12)
script.Button(Controller.down, duration=20)
script.Wait(1)
script.Roll()
script.Wait(21)
script.Button(Controller.down, duration=15)
script.Wait(1)
script.Roll()
script.Wait(8)
script.MoveLeftStick(320)
script.Button(Controller.X, duration=0)
script.Button(Controller.right, duration=15)
script.Wait(5)
script.Button(Controller.down, duration=15)
script.Wait(1)
script.Roll()
script.Wait(15)
script.MoveLeftStick(30)
script.Button(Controller.X, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=15)
script.Wait(15)
script.Button(Controller.left, duration=3)
script.Wait(3)
script.Button(Controller.A, duration=0)
script.Button(Controller.left, duration=15)
script.Wait(4)
script.MoveLeftStick(130)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=6)
script.Wait(8)
script.MoveLeftStick(170)
script.Button(Controller.X, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=24)
script.Wait(3)
script.Button(Controller.right, duration=15)
script.Wait(13)
script.Roll()
script.Wait(10)
script.MoveLeftStick(10)
script.Button(Controller.X, duration=0)
script.Wait(7)
script.Button(Controller.left, duration=6)
script.Button(Controller.down, duration=6)
script.Wait(6)
script.Wait(1)
script.Button(Controller.left, duration=27)
script.Button(Controller.down, duration=20)
script.Wait(1)
script.Roll()
script.Wait(21)
script.MoveLeftStick(180)
script.Button(Controller.B, duration=0)
script.Wait(4)
script.Button(Controller.A, duration=1)
script.Wait(1)
script.Button(Controller.down, duration=14)
script.Wait(1)
script.Button(Controller.right, duration=8)
script.Wait(11)
script.Roll()
script.Wait(5)
script.MoveLeftStick(10)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=20)
script.Button(Controller.left, duration=18)
script.Wait(15)
script.Roll()
script.Wait(17)
script.MoveLeftStick(296)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=15)
script.Button(Controller.right, duration=15)
script.Wait(11)
script.MoveLeftStick(320)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(8)
script.MoveLeftStick(292)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=8)
script.Button(Controller.left, duration=15)
script.Wait(8)
script.MoveLeftStick(240)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(2)
script.Button(Controller.B, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=9)
script.Wait(11)
script.Button(Controller.A, duration=1)
script.Wait(1)
script.Button(Controller.down, duration=15)
script.Wait(8)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Button(Controller.right, duration=100)
script.Wait(12)
script.Button(Controller.down, duration=17)
script.Wait(16)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=20)
script.Wait(16)
script.Roll()
script.Wait(13)
script.Button(Controller.X)
script.Wait(11)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.X)
script.Wait(11)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.X)
script.Wait(11)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()

script.save()
