# Bunker 2-2 7.82 made by Bar0ti https://youtu.be/my9mt2fhxJo
# Guaranteed to be improvable
# Take a path by going under the terry

from katas import Controller, Scripter
script = Scripter()

script.Button(Controller.left_shoulder, 0)
script.Wait(69)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0.8)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(9)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(8)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(15)
script.MoveLeftStick(0.8)
script.Button(Controller.X, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(3)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(14)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(14)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.B, duration=0)
script.Button(Controller.Y, duration=0)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.right, duration=7)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(5)
script.MoveLeftStick(130)
script.Button(Controller.B, duration=0)
script.Wait(5)
script.Button(Controller.right, duration=7)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(8)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(6)
script.Button(Controller.B, duration=0)
script.Wait(7)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(6)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(13)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(12)
script.MoveLeftStick(354)
script.Button(Controller.X, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(1)
script.Button(Controller.B, duration=0)
script.Wait(4)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Button(Controller.right, duration=20)
script.Wait(2)
script.Button(Controller.down, duration=15)
script.Wait(17)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(4)
script.MoveLeftStick(180)
script.Button(Controller.B, duration=0)
script.Wait(6)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(9)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.save()

#slow-mo
#script.Button(Controller.left_thumb, duration=0)

#scuffed slow-mo c-slashing timings
#script.MoveLeftStick(0.8)
#script.Button(Controller.X, duration=0)
#script.Wait(11)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(3)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()

#c-slash timings
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.MoveLeftStick(0)
#script.Button(Controller.X, duration=0)
#script.Wait(11)


