# HH-1 19.46 made by Bar0ti https://youtu.be/2H8HWIzYJxQ
# Maybe improvable
# The second bullet that hits HH is way sooner than the 1st one
# maybe there is that 1 frame early window at which you can hit HH earlier as well on the 1st hit

from katas import Controller, Scripter
script = Scripter()

#Bunker 2-3 script
script.Button(Controller.left_shoulder, 0)
script.Wait(69)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(5)
script.Button(Controller.left, duration=35)
script.Button(Controller.left_thumb, duration=0)
script.Button(Controller.A, duration=30)
script.Button(Controller.B, duration=0)
script.Wait(18)
script.MoveLeftStick(90)
script.Button(Controller.X, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=1)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(3)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(6)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0.8)
script.Button(Controller.X, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(6)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(14)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(8)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(8)
script.Button(Controller.right, duration=6)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(7)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(14)
script.MoveLeftStick(0.8)
script.Button(Controller.X, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.Button(Controller.right, duration=6)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(3)
script.Button(Controller.left, duration=6)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.MoveLeftStick(30)
script.Button(Controller.B, duration=0)
script.Wait(5)
script.Button(Controller.B, duration=0)
script.Wait(6)
script.Button(Controller.left, duration=6)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.MoveLeftStick(179.2)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(210)
script.Button(Controller.X, duration=0)
script.Wait(7)
script.Button(Controller.down, duration=6)
script.Button(Controller.right, duration=6)
script.Wait(6)
script.MoveLeftStick(266)
script.Button(Controller.X, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=8)
script.Button(Controller.right, duration=14)
script.Wait(10)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(354.2405)
script.Button(Controller.X, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.MoveLeftStick(0.8)
script.Button(Controller.X, duration=0)
script.Wait(3)
script.MoveLeftStick(240)
script.Button(Controller.B, duration=0)
script.Wait(8)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(8)
script.MoveLeftStick(330)
script.Button(Controller.X, duration=0)
script.Wait(2)
script.Wait(5)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(8)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()


#HH-1 dialogue
script.Wait(194)
script.Button(Controller.A, duration=0)
script.Wait(30)
script.Button(Controller.A, duration=0)
script.Wait(56)
script.Button(Controller.A, duration=0)
script.Wait(30)
script.Button(Controller.A, duration=0)
script.Wait(60)


#HH-1 script
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(7)
script.MoveLeftStick(0.6)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(8)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=0)
script.Wait(1)
script.Roll()
script.Wait(4)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(40)
script.Button(Controller.right, duration=24)
script.Wait(100)
script.Roll()
script.Wait(32)
script.Button(Controller.down, duration=0)
script.Button(Controller.left, duration=0)
script.Wait(1)
script.Roll()
script.Wait(32)
script.Button(Controller.down, duration=0)
script.Button(Controller.right, duration=0)
script.Wait(1)
script.Roll()
script.Wait(12)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=0)
script.Button(Controller.left, duration=0)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(179.6)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=1)
script.Button(Controller.right, duration=1)
script.Wait(1)
script.Roll()
script.Wait(8)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=0)
script.Wait(1)
script.Roll()
script.Wait(9)
script.MoveLeftStick(180)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.MoveLeftStick(180)
script.Button(Controller.X, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=0)
script.Wait(1)
script.Roll()
script.Wait(58)
script.Button(Controller.down, duration=0)
script.Wait(1)
script.Roll()
script.Wait(3)
script.Button(Controller.A, duration=0)
script.Wait(6)
script.Button(Controller.down, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=1)
script.Button(Controller.right, duration=1)
script.Wait(1)
script.Roll()
script.Wait(3)
script.Button(Controller.A, duration=0)
script.Wait(6)
script.Button(Controller.down, duration=0)
script.Wait(6)
script.Button(Controller.down, duration=1)
script.Button(Controller.left, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.Button(Controller.A, duration=0)
script.Wait(6)
script.Button(Controller.down, duration=0)
script.Wait(11)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=1)
script.Button(Controller.left, duration=1)
script.Wait(1)
script.Roll()
script.Wait(12)
script.MoveLeftStick(180)
script.Button(Controller.X, duration=0)
script.Wait(25)
script.Button(Controller.down, duration=1)
script.Button(Controller.right, duration=1)
script.Wait(1)
script.Roll()
script.Wait(3)
script.Button(Controller.A, duration=0)
script.Wait(6)
script.Button(Controller.down, duration=0)
script.Wait(16)
script.Button(Controller.down, duration=1)
script.Button(Controller.left, duration=1)
script.Wait(1)
script.Roll()
script.Wait(6)
script.Button(Controller.A, duration=0)
script.Wait(6)
script.Button(Controller.down, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=1)
script.Button(Controller.right, duration=1)
script.Wait(1)
script.Roll()
script.Wait(5)
script.Button(Controller.A, duration=0)
script.Wait(6)
script.Button(Controller.down, duration=0)
script.Wait(6)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(12)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(19)
script.Button(Controller.down, duration=1)
script.Button(Controller.left, duration=1)
script.Wait(1)
script.Roll()
script.Wait(9)
script.MoveLeftStick(180)
script.Button(Controller.X, duration=0)
script.Wait(6)
script.Button(Controller.down, duration=1)
script.Button(Controller.right, duration=1)
script.Wait(1)
script.Roll()
script.Wait(7)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(132)
script.Button(Controller.A, duration=26)
script.Wait(25)
script.MoveLeftStick(90)
script.Button(Controller.X, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=20)
script.save()
#41
#c-slash timings
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.MoveLeftStick(0)
#script.Button(Controller.X, duration=0)
#script.Wait(11)

#scuffed slow-mo c-slashing timings
#script.MoveLeftStick(0.6)
#script.Button(Controller.X, duration=0)
#script.Wait(11)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(8)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(3)
#script.Button(Controller.down, duration=0)
#script.Wait(1)
#script.Roll()
#script.Wait(10)

#slow-mo roll cancel timings
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(11)
#script.Button(Controller.right, duration=6)
#script.Button(Controller.A, duration=0)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(2)
#script.Button(Controller.down, duration=0)
#script.Wait(2)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()

#Roll cancel on stairs
#script.Button(Controller.right, duration=7)
#script.Button(Controller.A, duration=0)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(3)
#script.Button(Controller.down, duration=2)
#script.Wait(1)
#script.Roll()

#Early wall slide exit into a c-roll
#script.Button(Controller.left, duration=6)
#script.Wait(6)
#script.Button(Controller.right, duration=6)
#script.Button(Controller.down, duration=0)
#script.Wait(2)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
