# Hotel-2 4.52 made by Bar0ti https://youtu.be/G5mhiYNpncw
# Very unlikely to be improved
# maybe throw a pot in such a manner to break up the upper two terries

from katas import Controller, Scripter
script = Scripter()

script.Button(Controller.left_shoulder, 0)
script.Wait(83)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.right, duration=7)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.right, duration=7)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(7)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(7)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.right, duration=7)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.right, duration=7)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0.453)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.save()

#slow-mo
#script.Button(Controller.left_thumb, duration=0)

#c-slash timings
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.MoveLeftStick(0)
#script.Button(Controller.X, duration=0)
#script.Wait(11)

#scuffed slow-mo c-slashing timings
#script.MoveLeftStick(0.8)
#script.Button(Controller.X, duration=0)
#script.Wait(11)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(3)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)

#slow-mo roll cancel timings
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(11)
#script.Button(Controller.right, duration=6)
#script.Button(Controller.A, duration=0)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(2)
#script.Button(Controller.down, duration=1)
#script.Wait(3)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()

#Roll cancel on stairs
#script.Button(Controller.right, duration=7)
#script.Button(Controller.A, duration=0)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(3)
#script.Button(Controller.down, duration=2)
#script.Wait(1)
#script.Roll()
