# Studio-V 2nd part 5.45 made by Bar0ti https://youtu.be/Co275fG8SjM
# Maybe improvable
# Try other methods of slashing V 

from katas import Controller, Scripter
script = Scripter()

script.Button(Controller.left_shoulder, 0)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(7)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(20)
script.MoveLeftStick(250)
script.Button(Controller.X, duration=0)
script.Wait(9)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(22)
script.Button(Controller.left, duration=10)
script.Wait(45)
script.MoveLeftStick(250)
script.Button(Controller.X, duration=0)
script.Wait(20)
script.Button(Controller.A, duration=3)
script.Button(Controller.left, duration=60)
script.Wait(42)
script.MoveLeftStick(260)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=20)
script.Wait(20)
script.Button(Controller.A, duration=4)
script.Button(Controller.left, duration=60)
script.Wait(39)
script.MoveLeftStick(260)
script.Button(Controller.X, duration=0)
script.save()
#37
#slow-mo
#script.Button(Controller.left_thumb, duration=0)

#c-slash timings
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.MoveLeftStick(0)
#script.Button(Controller.X, duration=0)
#script.Wait(11)

#scuffed slow-mo c-slashing timings
#script.MoveLeftStick(0.8)
#script.Button(Controller.X, duration=0)
#script.Wait(11)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(3)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)

#slow-mo roll cancel timings
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(11)
#script.Button(Controller.right, duration=6)
#script.Button(Controller.A, duration=0)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(2)
#script.Button(Controller.down, duration=0)
#script.Wait(2)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()

#Roll cancel on stairs
#script.Button(Controller.right, duration=7)
#script.Button(Controller.A, duration=0)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(3)
#script.Button(Controller.down, duration=2)
#script.Wait(1)
#script.Roll()
