# Mansion-3 6.05 + 1.16 made by Bar0ti https://youtu.be/phUJh_9oQuo
# Guaranteed to be improvable
# Check the timing of slashing each enemy
# Check the timing of slashing the doors
# Falling down can be done better, by accelerating to the right for longer to reach the molly sooner
# Climbing can be probably improved
# Big maybe on letting the terry survive the door shutting

from katas import Controller, Scripter
script = Scripter()

script.Button(Controller.left_shoulder, 0)
script.Wait(2)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(7)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(11)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(7)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(7)
script.MoveLeftStick(354.22)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(7)
script.Button(Controller.right, duration=6)
script.Button(Controller.A, duration=3)
script.Wait(5)
script.Button(Controller.down, duration=12)
script.Wait(17)
script.Button(Controller.right, duration=10)
script.Wait(9)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Button(Controller.B, duration=0)
script.Button(Controller.left, duration=1)
script.Wait(1)
script.Roll()
script.Wait(1)
script.Button(Controller.B, duration=0)
script.Wait(1)
script.Button(Controller.A, duration=50)
script.Button(Controller.left_thumb, duration=0)
script.Wait(1)
script.Button(Controller.right, duration=36)
script.Wait(21)
script.MoveLeftStick(90)
script.Button(Controller.X, duration=0)
script.Wait(21)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(6)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(7)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(10)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.save()
