# Mansion-5 5.57 + 1.17 made by Bar0ti https://youtu.be/phUJh_9oQuo
# Guaranteed to be improvable
# Shorten each flamethrower shot
# Check the timing of slashing the doors
# Check other ways to kill the first gunner with flamethrower
# Non-restart strat maybe

from katas import Controller, Scripter
script = Scripter()

script.Button(Controller.left_shoulder, 0)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(22)
script.MoveLeftStick(93, duration=20)
script.Button(Controller.B, duration=20)
script.Button(Controller.right, duration=20)
script.Wait(5)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(22)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(6)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(7)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(13)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(8)
script.Button(Controller.right, duration=1)
script.Button(Controller.A, duration=20)
script.Button(Controller.left_thumb, duration=0)
script.Wait(1)
script.MoveLeftStick(240, duration=2)
script.Button(Controller.B, duration=2)
script.Wait(2)
script.Button(Controller.right, duration=12)
script.Wait(6)
script.MoveLeftStick(70)
script.Button(Controller.X, duration=0)
script.Wait(7)
script.MoveLeftStick(90, duration=5)
script.Button(Controller.B, duration=5)
script.Button(Controller.down, duration=12)
script.Wait(8)
script.MoveLeftStick(350)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(17)
script.MoveLeftStick(350)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(6)
script.Button(Controller.right, duration=20)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(9)
script.MoveLeftStick(263, duration=9)
script.Button(Controller.B, duration=9)
script.Wait(8)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.Button(Controller.right, duration=1)
script.Button(Controller.A, duration=20)
script.Button(Controller.left_thumb, duration=0)
script.Wait(5)
script.MoveLeftStick(80)
script.Button(Controller.X, duration=0)
script.Wait(7)
script.Button(Controller.B, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=8)
script.Button(Controller.right, duration=9)
script.Wait(10)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(4)
script.MoveLeftStick(121, duration=0)
script.Button(Controller.B, duration=0)
script.Wait(3)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Wait(1)
script.Roll()
script.Wait(200)
script.Button(Controller.A, duration=10)
script.save()

