# China-4 6.12 made by Bar0ti https://youtu.be/58eY7S0QI4o
# Most likely improvable
# Find better ways of throwing the items

from katas import Controller, Scripter
script = Scripter()


#China-3 script
script.Button(Controller.left_shoulder, 0)
script.Wait(70)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(7)
script.Button(Controller.right, duration=7)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(7)
script.Button(Controller.right, duration=7)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(7)
script.Button(Controller.right, duration=6)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(9)
script.MoveLeftStick(45)
script.Button(Controller.X, duration=0)
script.Button(Controller.right, duration=60)
script.Wait(19)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(14)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(13)
script.Button(Controller.right, duration=7)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=8)
script.Wait(7)
script.Button(Controller.B, duration=0)
script.MoveLeftStick(120)
script.Button(Controller.X, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=1)
script.Wait(3)
script.Button(Controller.left_thumb, duration=0)
script.Button(Controller.A, duration=20)
script.Wait(1)
script.Button(Controller.right, duration=1)
script.Wait(10)
script.MoveLeftStick(210)
script.Button(Controller.B, duration=0)
script.Wait(2)
script.MoveLeftStick(70)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=9)
script.Button(Controller.right, duration=12)
script.Wait(9)
script.MoveLeftStick(310)
script.Button(Controller.X, duration=0)
script.Wait(3)
script.Button(Controller.left_thumb, duration=0)
script.Button(Controller.A, duration=20)
script.Button(Controller.left, duration=1)
script.Wait(6)
script.MoveLeftStick(123)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.right, duration=10)
script.Wait(7)
script.MoveLeftStick(40)
script.Button(Controller.X, duration=0)
script.Wait(6)
script.Button(Controller.Y, duration=0)


script.Wait(103)


#China-4 script
script.Button(Controller.left_shoulder, )
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(7)
script.Button(Controller.right, duration=6)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(7)
script.MoveLeftStick(355)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.Button(Controller.right, duration=6)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.MoveLeftStick(350)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.right, duration=17)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=12)
script.Wait(17)
script.MoveLeftStick(290)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=11)
script.Button(Controller.left, duration=13)
script.Wait(14)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(1)
script.MoveLeftStick(147, duration=0)
script.Button(Controller.B, duration=0)
script.Wait(1)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(5)
script.Button(Controller.A, duration=10)
script.Wait(5)
script.Button(Controller.right, duration=4)
script.Wait(3)
script.MoveLeftStick(82)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.right, duration=7)
script.Wait(21)
script.Button(Controller.B, duration=0)
script.Wait(3)
script.MoveLeftStick(122)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=12)
script.Button(Controller.left, duration=12)
script.Wait(15)
script.MoveLeftStick(144.8, duration=0)
script.Button(Controller.B, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=1)
script.Button(Controller.right, duration=1)
script.Wait(1)
script.Roll()
script.Wait(5)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.MoveLeftStick(0.453)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(8)
script.MoveLeftStick(0.8)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(8)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.save()

#c-slash timings
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.MoveLeftStick(0)
#script.Button(Controller.X, duration=0)
#script.Wait(11)

#scuffed slow-mo c-slashing timings
#script.MoveLeftStick(0.8)
#script.Button(Controller.X, duration=0)
#script.Wait(11)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(3)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)

#slow-mo roll cancel timings
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(11)
#script.Button(Controller.right, duration=6)
#script.Button(Controller.A, duration=0)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(2)
#script.Button(Controller.down, duration=0)
#script.Wait(2)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()

#Roll cancel on stairs
#script.Button(Controller.right, duration=7)
#script.Button(Controller.A, duration=0)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(3)
#script.Button(Controller.down, duration=2)
#script.Wait(1)
#script.Roll()

#Early wall slide exit into a c-roll
#script.Button(Controller.left, duration=6)
#script.Wait(6)
#script.Button(Controller.right, duration=6)
#script.Button(Controller.down, duration=0)
#script.Wait(2)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
