# China-5 4.25 made by Bar0ti https://youtu.be/hoATl810RgM
# Guaranteed to be improvable

from katas import Controller, Scripter
script = Scripter()



#China-4 script
script.Button(Controller.left_shoulder, 0)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(7)
script.Button(Controller.right, duration=6)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(7)
script.MoveLeftStick(355)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.Button(Controller.right, duration=6)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.MoveLeftStick(350)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.right, duration=17)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=12)
script.Wait(17)
script.MoveLeftStick(290)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=11)
script.Button(Controller.left, duration=13)
script.Wait(14)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(1)
script.MoveLeftStick(147, duration=0)
script.Button(Controller.B, duration=0)
script.Wait(1)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(5)
script.Button(Controller.A, duration=10)
script.Wait(5)
script.Button(Controller.right, duration=4)
script.Wait(3)
script.MoveLeftStick(82)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.right, duration=7)
script.Wait(21)
script.Button(Controller.B, duration=0)
script.Wait(3)
script.MoveLeftStick(122)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=12)
script.Button(Controller.left, duration=12)
script.Wait(15)
script.MoveLeftStick(144.8, duration=0)
script.Button(Controller.B, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=1)
script.Button(Controller.right, duration=1)
script.Wait(1)
script.Roll()
script.Wait(5)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.MoveLeftStick(0.453)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(8)
script.MoveLeftStick(0.8)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(8)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)



script.Wait(32)


#China-5
script.Wait(32)
script.Button(Controller.left_thumb, duration=0)
script.Button(Controller.A, duration=30)
script.Button(Controller.right, duration=60)
script.Wait(3)
script.Button(Controller.B, duration=0)
script.Wait(12)
script.MoveLeftStick(80)
script.Button(Controller.X, duration=0)
script.Wait(16)
script.MoveLeftStick(358)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.right, duration=6)
script.Button(Controller.A, duration=0)
script.Button(Controller.left_thumb, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(16)
script.MoveLeftStick(330)
script.Button(Controller.X, duration=0)
script.Wait(2)
script.MoveLeftStick(0)
script.Button(Controller.B, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=15)
script.Button(Controller.right, duration=30)
script.Wait(1)
script.MoveLeftStick(320)
script.Button(Controller.B, duration=0)
script.Wait(23)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(6)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(9)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(6)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(11)
script.MoveLeftStick(0.8)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.left_thumb, duration=0)
script.Wait(3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(2)
script.MoveLeftStick(120)
script.Button(Controller.B, duration=0)
script.Wait(8)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.save()

#slow-mo
#script.Button(Controller.left_thumb, duration=0)

#scuffed slow-mo c-slashing timings
#script.MoveLeftStick(0.8)
#script.Button(Controller.X, duration=0)
#script.Wait(11)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(3)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)

#c-slash timings
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.MoveLeftStick(0)
#script.Button(Controller.X, duration=0)
#script.Wait(11)


