# Chinatown-8 7.79 made by Bar0ti https://youtu.be/DlWROcBVqXc
# In-game timer adjusted from 6.58 due to the TAS skipping an animation
# Guaranteed to be possible to be improved, I basically only checked 1 path of this room
# The ending is especially slow, if someone could find a way to alleviate that bottleneck it'd be great
# Possible ways of attempting it are:
# -you could possibly use a smoke and molotov to kill everyone in one go
# -try to deflect only one bullet from the gunner and use the statue and molotov to kill the remaining two enemies
# -improve the existing double deflect strat, as it very possible to improve it
# -smoke teleporter shenanigans

from katas import Controller, Scripter

script = Scripter()
script.Button(Controller.left_shoulder, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(12)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(3)
script.Button(Controller.A, duration=11)
script.Button(Controller.right, duration=10)
script.Wait(11)
script.MoveLeftStick(100)
script.Button(Controller.X, duration=0)
script.Button(Controller.left, duration=12)
script.Wait(19)
script.Button(Controller.A, duration=1)
script.Wait(9)
script.Button(Controller.down, duration=10)
script.Wait(1)
script.Roll()
script.Wait(20)
script.Button(Controller.A, duration=20)
script.Button(Controller.left, duration=20)
script.Wait(18)
script.MoveLeftStick(140)
script.Button(Controller.X, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Button(Controller.right, duration=3)
script.Roll()
script.Wait(10)
script.MoveLeftStick(350)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(12)
script.MoveLeftStick(230)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=22)
script.Button(Controller.left, duration=22)
script.Wait(23)
script.MoveLeftStick(230)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=22)
script.Button(Controller.left, duration=22)
script.Wait(12)
script.Roll()
script.Wait(9)
script.MoveLeftStick(180)
script.Button(Controller.X, duration=0)
script.Wait(14)
script.Button(Controller.right, duration=3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(10)
script.Button(Controller.right, duration=13)
script.Wait(28)
script.MoveLeftStick(20)
script.Button(Controller.X, duration=0)
script.Wait(2)
script.Button(Controller.right, duration=13)
script.Button(Controller.down, duration=6)
script.Wait(5)
script.Roll()
script.Wait(10)
script.Button(Controller.A, duration=10)
script.Wait(10)
script.MoveLeftStick(60)
script.Button(Controller.X, duration=0)
script.Wait(2)
script.MoveLeftStick(180)
script.Button(Controller.B, duration=0)
script.Wait(1)
script.Button(Controller.right, duration=13)
script.Button(Controller.down, duration=8)
script.Wait(6)
script.Roll()
script.Wait(3)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=8)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.save()
