# Dragon-1 12.30 made by Bar0ti https://youtu.be/Gr4fpJH3Vvs
# Unlikely to be improved
# With the current strat you can only improve the final dragon dash, if you can slash
# the gunner more to the left you maybe will be able to save some time
# One other very unlikely change is to open the doors via a kick and not a slash
# if you can get there quickly enough might save a few frames
# One change to the strat is to after opening the doors is to deflect two shotgun bullets

# To run the dragon-1 room you will need to start the script in china-8

from katas import Controller, Scripter
script = Scripter()

# China-8 script 
script.Button(Controller.left_shoulder, duration=0)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(12)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=9)
script.Wait(1)
script.Roll()
script.Wait(3)
script.Button(Controller.A, duration=11)
script.Button(Controller.right, duration=10)
script.Wait(11)
script.MoveLeftStick(100)
script.Button(Controller.X, duration=0)
script.Button(Controller.left, duration=12)
script.Wait(19)
script.Button(Controller.A, duration=1)
script.Wait(9)
script.Button(Controller.down, duration=10)
script.Wait(1)
script.Roll()
script.Wait(20)
script.Button(Controller.A, duration=20)
script.Button(Controller.left, duration=20)
script.Wait(18)
script.MoveLeftStick(140)
script.Button(Controller.X, duration=0)
script.Wait(12)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Button(Controller.right, duration=3)
script.Roll()
script.Wait(10)
script.MoveLeftStick(350)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(11)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(12)
script.MoveLeftStick(230)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=22)
script.Button(Controller.left, duration=22)
script.Wait(23)
script.MoveLeftStick(230)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=22)
script.Button(Controller.left, duration=22)
script.Wait(12)
script.Roll()
script.Wait(9)
script.MoveLeftStick(180)
script.Button(Controller.X, duration=0)
script.Wait(14)
script.Button(Controller.right, duration=3)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(10)
script.Button(Controller.right, duration=13)
script.Wait(28)
script.MoveLeftStick(20)
script.Button(Controller.X, duration=0)
script.Wait(2)
script.Button(Controller.right, duration=13)
script.Button(Controller.down, duration=6)
script.Wait(5)
script.Roll()
script.Wait(10)
script.Button(Controller.A, duration=10)
script.Wait(10)
script.MoveLeftStick(60)
script.Button(Controller.X, duration=0)
script.Wait(2)
script.MoveLeftStick(180)
script.Button(Controller.B, duration=0)
script.Wait(1)
script.Button(Controller.right, duration=13)
script.Button(Controller.down, duration=8)
script.Wait(6)
script.Roll()
script.Wait(3)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=8)
script.Wait(1)
script.Roll()
script.Wait(10)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)

#Dialogue button presses
script.Wait(186)
script.Button(Controller.A, duration=0)
script.Wait(30)
script.Button(Controller.A, duration=0)
script.Wait(53)
script.Button(Controller.A, duration=0)
script.Wait(30)
script.Button(Controller.A, duration=0)
script.Wait(56)
script.Button(Controller.A, duration=0)
script.Wait(30)
script.Button(Controller.A, duration=0)
script.Wait(53)
script.Button(Controller.A, duration=0)
script.Wait(30)
script.Button(Controller.A, duration=0)
script.Wait(122)

#Active gameplay of dragon-1 
script.MoveLeftStick(180)
script.Button(Controller.B, duration=0)
script.Button(Controller.left, duration=7)
script.Wait(5)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(10)
script.Button(Controller.left, duration=7)
script.Button(Controller.A, duration=0)
script.Wait(5)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(6)
script.Button(Controller.right, duration=32)
script.Button(Controller.A, duration=32)
script.Wait(17)
script.Button(Controller.down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(23)
script.Button(Controller.left, duration=1)
script.Wait(5)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.MoveLeftStick(0)
script.Button(Controller.B, duration=0)
script.Wait(3)
script.Button(Controller.left, duration=4)
script.Wait(2)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(21)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(21)
script.Button(Controller.down, duration=1)
script.Wait(1)
script.Roll()
script.Wait(13)
script.Button(Controller.A, duration=0)
script.Wait(8)
script.Button(Controller.down, duration=1)
script.Wait(3)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(2)
script.MoveLeftStick(180)
script.Button(Controller.B, duration=0)

script.save()
#slow-mo
#script.Button(Controller.left_thumb, duration=0)

#c-slash timings
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.MoveLeftStick(0)
#script.Button(Controller.X, duration=0)
#script.Wait(11)

#scuffed slow-mo c-slashing timings
#script.MoveLeftStick(0.8)
#script.Button(Controller.X, duration=0)
#script.Wait(11)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(3)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)

#slow-mo roll cancel timings
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(11)
#script.Button(Controller.right, duration=6)
#script.Button(Controller.A, duration=0)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(2)
#script.Button(Controller.down, duration=1)
#script.Wait(3)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()

#Roll cancel on stairs
#script.Button(Controller.right, duration=7)
#script.Button(Controller.A, duration=0)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(3)
#script.Button(Controller.down, duration=2)
#script.Wait(1)
#script.Roll()
