#3 other variants of bunker 1-5 that have a chnace of being faster
#a fourth variant is to use a ricky boost at the beginning of the room

from katas import Controller, Scripter

script = Scripter()
script.Button(Controller.left_shoulder, duration=0)
script.Wait(2)
script.Button(Controller.dpad_down, duration=6)
script.Wait(1)
script.Roll()
script.Wait(19)
script.MoveLeftStick(180)
script.Button(Controller.X, duration=0)
script.Wait(6)
script.Roll()
script.Wait(18)
script.MoveLeftStick(180)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Roll()
script.Wait(11)
script.MoveLeftStick(145)
script.Button(Controller.X, duration=0)
script.Wait(4)
script.Button(Controller.dpad_down, duration=2)
script.Wait(1)
script.Roll()
script.Wait(9)
script.Button(Controller.A, duration=1)
script.Wait(4)
script.Button(Controller.dpad_down, duration=3)
script.Wait(2)
script.Roll()
script.Wait(4)
script.MoveLeftStick(40)
script.Button(Controller.B, duration=0)
#change the variable ChangeStrat to use other variations of this room
#ChangeStrat = 1 the end is done with roll and slash to the elevator 6.88
#ChangeStrat = 2 the end is done with roll cancel 6.90
#ChangeStrat = 3 the end is done with frame perfect crouch roll work in progress
ChangeStrat = 3
if ChangeStrat == 1:
    script.Wait(14)
    script.MoveLeftStick(140)
    script.Button(Controller.X, duration=0)
    script.Wait(3)
    script.Button(Controller.dpad_down, duration=2)
    script.Wait(1)
    script.Roll()
    script.Wait(18)
    script.Button(Controller.Y, duration=0)
    script.Wait(3)
    script.Wait(1)
    script.Button(Controller.X, duration=0)
    script.Wait(10)
    script.Button(Controller.dpad_down, duration=2)
    script.Wait(1)
    script.Roll()
if ChangeStrat == 2:
    script.Wait(18)
    script.MoveLeftStick(140)
    script.Button(Controller.X, duration=0)
    script.Wait(3)
    script.Button(Controller.dpad_down, duration=2)
    script.Wait(1)
    script.Roll()
    script.Wait(16)
    script.Button(Controller.A, duration=1)
    script.Wait(1)
    script.Button(Controller.Y, duration=0)
    script.Wait(1)    
    script.Button(Controller.dpad_down, duration=2)
    script.Wait(2)
    script.Roll()
if ChangeStrat == 3:
    script.Wait(18)
    script.Button(Controller.dpad_down, duration=2)
    script.Wait(1)
    script.Roll()
    script.Wait(2)
    script.MoveLeftStick(165)
    script.Button(Controller.X, duration=0)
    script.Wait(6)
    script.Button(Controller.dpad_down, duration=2)
    script.Wait(2)
    script.Roll()
    script.Wait(9)
    script.Button(Controller.Y, duration=0)
script.save()
