# Slaughter-1 11.47 made by Bar0ti https://youtu.be/WJe4Z_6ECII
# Maybe improvable

from katas import Controller, Scripter
script = Scripter()

script.Button(Controller.left_shoulder, 0)

a = 2



if a == 1:
    script.Wait(86)
    script.Button(Controller.left, duration=70)
    script.Wait(90)
    script.MoveLeftStick(180)
    script.Button(Controller.X, duration=0)
    script.Wait(10)
    script.Button(Controller.down, duration=13)
    script.Wait(75)
    script.MoveLeftStick(135)
    script.Button(Controller.X, duration=0)
    script.Wait(1)
    script.Button(Controller.up, duration=18)
    script.Wait(15)
    script.MoveLeftStick(150)
    script.Button(Controller.X, duration=0)
    script.Wait(1)
    script.Button(Controller.up, duration=15)
    script.Button(Controller.right, duration=180)
    script.Wait(189)
    script.MoveLeftStick(310)
    script.Button(Controller.X, duration=0)
    script.Wait(1)
    script.Button(Controller.down, duration=18)
    script.Wait(15)
    script.MoveLeftStick(270)
    script.Button(Controller.X, duration=0)
    script.Wait(1)
    script.Button(Controller.up, duration=28)
    script.Wait(30)
    script.MoveLeftStick(200)
    script.Button(Controller.B, duration=0)
    script.Wait(1)
    script.Button(Controller.up, duration=9)
    script.Wait(30)
    script.MoveLeftStick(0)
    script.Button(Controller.X, duration=0)

script.Wait(1)
script.Button(Controller.right, duration=80)
script.Button(Controller.down, duration=7)
script.Wait(141)
script.MoveLeftStick(30)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.up, duration=15)
script.Wait(15)
script.MoveLeftStick(30)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.left, duration=170)
script.Button(Controller.down, duration=14)
script.Wait(70)
script.MoveLeftStick(180)
script.Button(Controller.X, duration=0)
script.Wait(14)
script.Button(Controller.down, duration=14)
script.Wait(80)
script.MoveLeftStick(140)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.up, duration=15)
script.Wait(15)
script.MoveLeftStick(140)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.down, duration=20)
script.Button(Controller.right, duration=70)
script.Wait(70)
script.MoveLeftStick(0)
script.Button(Controller.X, duration=0)
script.Wait(1)
script.Button(Controller.left, duration=80)
script.Button(Controller.down, duration=19)
script.Wait(88)
script.MoveLeftStick(10)
script.Button(Controller.B, duration=0)
script.Wait(1)
script.Button(Controller.left, duration=2)
script.Wait(5)
script.MoveLeftStick(150)
script.Button(Controller.X, duration=0)
script.Wait(2)
script.Button(Controller.up, duration=18)
script.Wait(18)
script.MoveLeftStick(90)
script.Button(Controller.X, duration=0)
script.Wait(20)
script.Button(Controller.right, duration=180)
script.Button(Controller.down, duration=55)
script.Wait(70)
script.Button(Controller.up, duration=33)
script.Wait(268)
script.Button(Controller.down, duration=12)
script.Wait(25)
script.Button(Controller.down, duration=10)
script.Wait(23)
script.Button(Controller.down, duration=10)
script.save()
#610 880


#c-slash timings
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.MoveLeftStick(0)
#script.Button(Controller.X, duration=0)
#script.Wait(11)
#59
#scuffed slow-mo c-slashing timings
#script.MoveLeftStick(0.8)
#script.Button(Controller.X, duration=0)
#script.Wait(11)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(3)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(10)

#slow-mo roll cancel timings
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()
#script.Wait(11)
#script.Button(Controller.right, duration=6)
#script.Button(Controller.A, duration=0)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(2)
#script.Button(Controller.down, duration=0)
#script.Wait(2)
#script.Button(Controller.down, duration=1)
#script.Wait(1)
#script.Roll()

#Roll cancel on stairs
#script.Button(Controller.right, duration=7)
#script.Button(Controller.A, duration=0)
#script.Button(Controller.left_thumb, duration=0)
#script.Wait(3)
#script.Button(Controller.down, duration=2)
#script.Wait(1)
#script.Roll()
